MODEL:
  NAME: 'lem_tran_base_patch16'
  CHECKPOINT_PATH: 'checkpoints/mae_inet_lup_vitb_ep800_ratio_optimized.pth'

OUTPUT_DIR: 'runs/finetune/MSMT17/mae_inet_lup_vitb_ep800_ratio_optimized/lem_tran'